---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name.app}}
  labels:
    app: {{.Values.name.app}}
    namespace: {{.Values.namespece}}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name.app}}
      monitor: "true"
      
  template:
    metadata:
      labels:
        app: {{.Values.name.app}}
        monitor: "true"
    spec:
      serviceAccountName: {{.Values.name.service_account}}
      containers:
      - name: {{.Values.name.app}}
        image: {{.Values.deployment.image}}:{{.Values.deployment.tag}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{.Values.network.port}}
        - containerPort:  8001
        livenessProbe:
          httpGet:
            path: /healthz
            port: 4040
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4040 
        startupProbe:
          httpGet:
            path: /healthz
            port: 4040
      env:
        resources:
          limits:
            cpu: {{.Values.deployment.resources.cpu_limit}}
            memory: {{.Values.deployment.resources.memory_limit}}
          requests:
            cpu: {{.Values.deployment.resources.cpu_request}}
            memory: {{.Values.deployment.resources.memory_request}}   
      
  
