---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.name.service_account}}
  namespace: {{.Values.namespece}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Values.namespece}}
  name: {{.Values.name.role}}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "create", "delete", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "delete", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.name.roleBinding}}
  namespace: {{.Values.namespece}}
subjects:
- kind: ServiceAccount
  name: {{.Values.name.service_account}}
  namespace: {{.Values.namespece}}
roleRef:
  kind: Role
  name: {{.Values.name.role}}
  apiGroup: rbac.authorization.k8s.io