apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-server
  template:
    metadata:
      labels:
        app: health-server
    spec:
      containers:
      - name: health-server
        image: aidawm/health_server:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: health-server-service
spec:
  selector:
    app: health-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
